<?php
/**
 * Created by Digital-Solution.Ru web-studio.
 * https://digital-solution.ru
 * support@digital-solution.ru
 */

namespace framework\components\rbac;


use framework\components\db\ActiveRecord;
use framework\components\db\SqlBuilder;

class Permission extends ActiveRecord
{
    const RBAC_RELATION_PERMISSION_IN_PERMISSION = 'rrpip';
    const RBAC_RELATION_TABLE = 'rbac_relation';

    protected $_relations = false;



    public function attributeLabels()
    {
        return array_merge(['slug' => 'Метка полномочия', 'name' => 'Название полномочия', 'description' => 'Описание полномочия'],parent::attributeLabels()); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [$this->getFields(), 'safe']
        ];
    }
}