<?php

/**
 * Created by Digital-Solution.Ru web-studio.
 * https://digital-solution.ru
 * support@digital-solution.ru
 */
namespace framework\models;

use framework\components\db\ActiveRecord;
use framework\components\db\SqlBuilder;

class Modules extends ActiveRecord
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public static function getByName($name)
    {
        return static::find()->where([
            ['name' => $name],
            ['status' => 1]
        ])->one();
    }

    public static function getList()
    {
        $sql = new SqlBuilder();
        $sql->select(Modules::tableName())->fields('name')->where(['status' => 1]);

        $array = $sql->row();

        if(!empty($array))
        {
            foreach ($array as $item)
                $out[] = $item['name'];
        }

        return $out;
    }
}
